DROP USER tdrep2 CASCADE;
DROP USER tdapp2 CASCADE;
DROP USER tdrep2_user CASCADE;

CREATE USER tdrep2 IDENTIFIED BY tdrep2;
GRANT CONNECT TO tdrep2;
CREATE USER tdapp2 IDENTIFIED BY tdapp2;
GRANT CONNECT TO tdapp2;
CREATE USER tdrep2_user IDENTIFIED BY tdrep2_user;
GRANT CONNECT TO tdrep2_user;

GRANT EXECUTE ON sys.utl_mail TO tdapp2
/