CREATE OR REPLACE VIEW tdinc.feed_ot 
OF tdinc.feed
WITH object identifier (filehub_id)
as
SELECT cast('runtime' AS VARCHAR2(10)) runmode,
       filehub_id,
       filehub_name,
       filehub_group,
       filehub_type,
       object_owner,
       object_name,
       directory,
       dirpath,
       filename,
       dirpath || '/' || filename filepath,
       arch_directory,
       arch_dirpath,
       NULL arch_filename,
       null arch_filepath,
       file_datestamp,
       min_bytes,
       max_bytes,
       baseurl,
       NULL file_url,
       passphrase,
       source_directory,
       source_dirpath,
       source_regexp,
       regexp_options,
       source_policy,
       required,
       reject_limit
  FROM (SELECT filehub_id,
               filehub_name,
               filehub_group,
               filehub_type,
               object_owner,
               object_name,
               directory,
	       coreutils.get_dir_path (directory) dirpath,
               filename,
	       arch_directory,
	       coreutils.get_dir_path (arch_directory) arch_dirpath,
	       file_datestamp,
               min_bytes,
               max_bytes,
               baseurl,
	       passphrase,
	       source_directory,
	       coreutils.get_dir_path (source_directory) source_dirpath,
	       source_regexp,
	       regexp_options,
	       source_policy,
	       required,
	       reject_limit
          FROM tdinc.filehub_conf
	 WHERE REGEXP_LIKE (filehub_type, '^feed$', 'i'));