CREATE OR REPLACE TYPE tdinc.basetype AS OBJECT (
   DEBUG           VARCHAR2 (1),
   MEMBER FUNCTION DEBUG_MODE
      RETURN BOOLEAN,
   MEMBER PROCEDURE DEBUG_MODE (p_debug BOOLEAN DEFAULT FALSE)
)
NOT FINAL;
/