CREATE OR REPLACE TYPE tdinc.notify AS OBJECT (
   notify_type      VARCHAR2 (10),
   notify_type_id   NUMBER,
   MESSAGE          VARCHAR2 (2000),
   subject          VARCHAR2 (100),
   DEBUG            VARCHAR2 (1),
   CONSTRUCTOR FUNCTION notify (p_debug BOOLEAN DEFAULT FALSE)
      RETURN SELF AS RESULT,
   MEMBER FUNCTION DEBUG_MODE
      RETURN BOOLEAN,
   MEMBER PROCEDURE DEBUG_MODE (p_debug BOOLEAN DEFAULT FALSE),
   MEMBER PROCEDURE send,
   MEMBER PROCEDURE email
)
NOT FINAL;
/