INSERT INTO tdinc.filehub_conf
       ( filehub_id, 
	 filehub_name, 
	 filehub_group, 
	 filehub_type, 
	 object_owner, 
	 object_name, 
	 directory, 
	 filename, 
	 arch_directory, 
	 min_bytes, 
	 max_bytes, 
	 file_datestamp, 
	 notification, 
	 source_directory, 
	 source_regexp, 
	 regexp_options, 
	 multi_files_action, 
	 file_requirement, 
	 dateformat, 
	 timestampformat, 
	 delimiter, 
	 quotechar, 
	 headers, 
	 created_user, 
	 created_dt, 
	 modified_user, 
	 modified_dt)
       SELECT tdinc.filehub_conf_seq.nextval,
	      extract,
	      extract||' group',
	      'extract',
	      owner, 
	      object,
	      dirname, 
	      filebase||'.'||filext, 
	      arcdirname,
	      0,
	      0,
	      datestamp, 
	      'notify',
	      NULL,
	      NULL,
	      NULL,
	      NULL,
	      NULL,
	      dateformat,
	      dateformat, 
	      delimiter, 
	      quotechar,
	      CASE headers
	      WHEN 'Y' THEN 'include'
	      ELSE 'exclude'
	      END headers, 
	      created_user, 
	      created_dt, 
	      modified_user, 
	      modified_dt
	 FROM common.gen_extract_conf
	WHERE arcdirname IS NOT null
/