-- create role for this repository
DROP ROLE &1._sel;
CREATE ROLE &1._sel;
DROP ROLE &1._adm;
CREATE ROLE &1._adm;


GRANT SELECT ON COUNT_TABLE TO &1._sel;
GRANT SELECT,UPDATE,DELETE,INSERT ON COUNT_TABLE TO &1._adm;

GRANT SELECT ON DIR_LIST TO &1._sel;
GRANT SELECT,UPDATE,DELETE,INSERT ON DIR_LIST TO &1._adm;

GRANT SELECT ON FILEHUB_CONF TO &1._sel;
GRANT SELECT,UPDATE,DELETE,INSERT ON FILEHUB_CONF TO &1._adm;
GRANT SELECT ON FILEHUB_CONF_SEQ TO &1._sel;
GRANT SELECT ON FILEHUB_CONF_SEQ TO &1._adm;

GRANT SELECT ON FILEHUB_DETAIL TO &1._sel;
GRANT SELECT,UPDATE,DELETE,INSERT ON FILEHUB_DETAIL TO &1._adm;
GRANT SELECT ON filehub_detail_seq TO &1._sel;
GRANT SELECT ON filehub_detail_seq TO &1._adm;

GRANT SELECT ON FILEHUB_OBJ_DETAIL TO &1._sel;
GRANT SELECT,UPDATE,DELETE,INSERT ON FILEHUB_OBJ_DETAIL TO &1._adm;
GRANT SELECT ON filehub_obj_detail_seq TO &1._sel;
GRANT SELECT ON filehub_obj_detail_seq TO &1._adm;

GRANT SELECT ON LOGGING_CONF TO &1._sel;
GRANT SELECT,UPDATE,DELETE,INSERT ON LOGGING_CONF TO &1._adm;
GRANT SELECT ON logging_conf_seq TO &1._sel;
GRANT SELECT ON logging_conf_seq TO &1._adm;

GRANT SELECT ON LOG_TABLE TO &1._sel;
GRANT SELECT,UPDATE,DELETE,INSERT ON LOG_TABLE TO &1._adm;

GRANT SELECT ON NOTIFY_CONF TO &1._sel;
GRANT SELECT,UPDATE,DELETE,INSERT ON NOTIFY_CONF TO &1._adm;
GRANT SELECT ON notify_conf_seq TO &1._sel;
GRANT SELECT ON notify_conf_seq TO &1._adm;

GRANT SELECT ON PARAMETER_CONF TO &1._sel;
GRANT SELECT,UPDATE,DELETE,INSERT ON PARAMETER_CONF TO &1._adm;
GRANT SELECT ON PARAMETER_CONF_SEQ TO &1._sel;
GRANT SELECT ON PARAMETER_CONF_SEQ TO &1._adm;

GRANT SELECT ON PARTNAME TO &1._sel;
GRANT SELECT,UPDATE,DELETE,INSERT ON PARTNAME TO &1._adm;

GRANT SELECT ON REGISTRATION_CONF TO &1._sel;
GRANT SELECT,UPDATE,DELETE,INSERT ON REGISTRATION_CONF TO &1._adm;
GRANT SELECT ON REGISTRATION_CONF_SEQ TO &1._sel;
GRANT SELECT ON REGISTRATION_CONF_SEQ TO &1._adm;

GRANT SELECT ON RUNMODE_CONF TO &1._sel;
GRANT SELECT,UPDATE,DELETE,INSERT ON RUNMODE_CONF TO &1._adm;
GRANT SELECT ON RUNMODE_CONF_SEQ TO &1._sel;
GRANT SELECT ON RUNMODE_CONF_SEQ TO &1._adm;
