insert into dimension_conf(owner,table_name,source_owner,source_object,replace_method,sequence_owner,sequence_name) values ('stewart','test_dim','stewart','test_stg','exchange','stewart','test_dim_seq');
insert into column_conf(owner,table_name,column_name,column_type) values ('stewart','test_dim','test_key','surrogate key');
insert into column_conf(owner,table_name,column_name,column_type) values ('stewart','test_dim','birthdate','scd type 1');
insert into column_conf(owner,table_name,column_name,column_type) values ('stewart','test_dim','name','scd type 2');
insert into column_conf(owner,table_name,column_name,column_type) values ('stewart','test_dim','zip','scd type 2');
insert into column_conf(owner,table_name,column_name,column_type) values ('stewart','test_dim','zip_plus4','scd type 2');
insert into column_conf(owner,table_name,column_name,column_type) values ('stewart','test_dim','nat_key','natural key');
insert into column_conf(owner,table_name,column_name,column_type) values ('stewart','test_dim','effect_start_dt','effective start date');
insert into column_conf(owner,table_name,column_name,column_type) values ('stewart','test_dim','effect_end_dt','effective end date');
insert into column_conf(owner,table_name,column_name,column_type) values ('stewart','test_dim','current_ind','current indicator');
