SET echo on

DROP TABLESPACE tdrep
     INCLUDING CONTENTS AND datafiles
/

CREATE TABLESPACE tdrep
DATAFILE '/u01/oradata/tdrep_01.dbf'
SIZE 1M
AUTOEXTEND ON NEXT 1M MAXSIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
