SET echo on

DROP TABLESPACE tdsys
     INCLUDING CONTENTS AND datafiles
/

CREATE TABLESPACE tdsys
DATAFILE '/u01/oradata/tdsys_01.dbf'
SIZE 1M
AUTOEXTEND ON NEXT 1M MAXSIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
