DROP TABLE EFW.EXTRACT_CONF CASCADE CONSTRAINTS
/

CREATE TABLE EFW.EXTRACT_CONF
(
  EXTRACT        VARCHAR2(1024)            NOT NULL,
  OBJECT         VARCHAR2(30)              NOT NULL,
  OWNER          VARCHAR2(30)              NOT NULL,
  FILEBASE       VARCHAR2(30)              NOT NULL,
  FILEXT         VARCHAR2(6)               DEFAULT '.csv',
  DATESTAMP      VARCHAR2(30)              DEFAULT 'MMDDYYYY',
  DATEFORMAT     VARCHAR2(30)              DEFAULT 'MM/DD/YYYY',
  DIRNAME        VARCHAR2(30)              NOT NULL,
  STGDIRNAME     VARCHAR2(30),
  DELIMITER      VARCHAR2(5)               DEFAULT ',',
  QUOTECHAR      VARCHAR2(1),
  SENDER         VARCHAR2(1024),
  RECIPIENTS     VARCHAR2(2000),
  BASEURL        VARCHAR2(255),
  HEADERS        VARCHAR2(1),
  SENDMAIL       VARCHAR2(1),
  ARCDIRNAME     VARCHAR2(30),
  CREATED_USER   VARCHAR2(30),
  CREATED_DT     DATE,
  MODIFIED_USER  VARCHAR2(30),
  MODIFIED_DT    DATE
)
TABLESPACE COMMON_DATA
/


CREATE UNIQUE INDEX EFW.EXTRACT_CONF_PK ON EFW.GEN_EXTRACT_CONF
(EXTRACT)
LOGGING
TABLESPACE efw
NOPARALLEL
/

ALTER TABLE EFW.EXTRACT_CONF ADD (
  CONSTRAINT EXTRACT_CONF_PK
 PRIMARY KEY
 (EXTRACT)
    USING INDEX 
    TABLESPACE efw)
/